# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: SSH@0
  inputs:
    sshEndpoint: 'e795ce5d-6452-4fce-bafc-3ae1870485df'
    runOptions: 'commands'
    commands: 'git add out/ && git commit -m "building project" && git push origin master' 

- script: |
    npm install
    npm run build
    npm run export
  displayName: 'npm install then build and export'
