# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm run export
  displayName: 'npm install then build and export'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/home/vsts/work/1/s/.next'
    ArtifactName: 'build-test'
    ArtifactType: 'FilePath'
    TargetPath: '/home/vsts/work/1/s/.next'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'e795ce5d-6452-4fce-bafc-3ae1870485df'
    sourceFolder: '/home/vsts/work/1/s/.next'
    targetFolder: '/home2/hpier/flexinbows.taranitup.club/testing'
    cleanTargetFolder: true


